version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    image: url-shortener-front
