version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000" # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=production
    image: url-shortener-app
