version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # Mount the host directory into the container
      - /app/node_modules # Use a separate node_modules directory in the container
    ports:
      - "5000:5000" # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run dev # Start the development server
    image: url-shortener-app-dev
